trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    cd test/Pipelines/doyinsolass.pipeline_template1  # Navigate to the directory containing your .csproj or .sln file
    dotnet restore
    dotnet build
    dotnet test
  displayName: 'Run .NET CLI commands'