trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '5.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: |
    echo "Current Directory:"
    pwd
    echo "Contents of test/Pipelines:"
    ls -la test/Pipelines
    cd doyinsolass/pipeline_template1/azure-pipelines.yml
    echo "Contents of doyinsolass.pipeline_template1:"
    ls -la
    dotnet restore
    dotnet build
    dotnet test
  displayName: 'Run .NET CLI commands'